# /efi and /boot stay as empty mount points so gpt-auto mounts the ESP there (needed by systemd-bless-boot).
[Partition]
Type=root
Format=ext4
CopyFiles=/
ExcludeFiles=/usr
ExcludeFiles=/efi/
ExcludeFiles=/boot/
SizeMinBytes=1G
