package loops

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"
)

// CorpusItem is one published attack text from a vendored corpus
// (assurance/corpora, built by tools/corpus.py). No item is written or
// generated by a model (D-067).
type CorpusItem struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// LoadCorpus reads a corpus's items.json.
func LoadCorpus(path string) ([]CorpusItem, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c struct {
		Items []CorpusItem `json:"items"`
	}
	if err := json.Unmarshal(b, &c); err != nil {
		return nil, fmt.Errorf("corpus %s: %w", path, err)
	}
	if len(c.Items) == 0 {
		return nil, fmt.Errorf("corpus %s: no items", path)
	}
	for _, it := range c.Items {
		if it.ID == "" || it.Text == "" {
			return nil, fmt.Errorf("corpus %s: an item lacks an id or text", path)
		}
	}
	return c.Items, nil
}

// ClosedCheck is one fixed-pattern check (ARC-2) the corpus replays
// against: CH-19's code filter, the commitment filter, the alert
// patterns, labels. Hit reports whether the check catches or refuses a
// text; Payload is what it must catch however an attack text surrounds it.
type ClosedCheck struct {
	Name    string // what the owner calls it: "code filter"
	Payload string
	Hit     func(text string) bool
}

// The placeholder PromptInject puts where its attack wants its own text.
const corpusSlot = "{REPLACE_rogue_string}"

// CorpusProbe replays published injection texts as untrusted input
// through the closed checks (LOOP-7). Each item carries each check's
// payload, in the attack's own slot or after its text; a check that no
// longer hits is a High finding on that item.
type CorpusProbe struct {
	Interval time.Duration
	Items    []CorpusItem
	Checks   []ClosedCheck
}

func (p *CorpusProbe) Check() Check         { return CheckCorpus }
func (p *CorpusProbe) Every() time.Duration { return p.Interval }

// Run checks every item against every check. A check that misses its bare
// payload is broken, and the run is an error that reports nothing.
func (p *CorpusProbe) Run(ctx context.Context) (ProbeResult, error) {
	if len(p.Items) == 0 || len(p.Checks) == 0 {
		return ProbeResult{}, errors.New("corpus probe: no items or checks")
	}
	for _, c := range p.Checks {
		if !c.Hit(c.Payload) {
			return ProbeResult{}, fmt.Errorf("corpus probe: %s misses its own payload", c.Name)
		}
	}
	var res ProbeResult
	for _, it := range p.Items {
		if err := ctx.Err(); err != nil {
			return ProbeResult{}, err
		}
		for _, c := range p.Checks {
			if !c.Hit(replay(it.Text, c.Payload)) {
				res.Found = append(res.Found, Finding{Check: CheckCorpus, Subject: it.ID, Detail: c.Name, Severity: High})
			}
		}
		res.Checked = append(res.Checked, it.ID)
	}
	return res, nil
}

func replay(text, payload string) string {
	if strings.Contains(text, corpusSlot) {
		return strings.ReplaceAll(text, corpusSlot, payload)
	}
	return text + "\n" + payload
}
