#!/usr/bin/env python3
"""Work items as GitHub issues; BOARD.md generated from them (SIM-repo-1, briefs/SIM.md).

One issue per live BOARD row. The issue is the record; its labels are the queryable index:
  work-item        marks the issue as a BOARD row
  state:<state>    the row's state, one of metrics.STATES; the only label rendering reads
  tier:A|B|C       risk tier, when the row names one ("tier A", or "(B; ..." in its state)
  class:<class>    blocker, release or later (OPERATING §2); release rows as doclint finds them
  lane:<team>      the docs/LANES.md team that builds it; primary unless the row names another
  gate:mark        merge waits on Mark beyond the reviews ("Mark approves", "owner to confirm")
The title is "<ID>: <package text>" and is the row's key. The body carries the row itself in a
fenced `board-row` JSON block: its section heading, its middle cells and the text after the
state word. Rows render in issue-number order within their section, so the migration creates
issues in BOARD order and a new issue lands at the end of its section.

BOARD.md's headings, prose and table headers stay in the file as the skeleton; rendering
replaces its rows with the live issues. merged and dropped rows are terminal and leave the
board (SIM-repo-2 archives them). Each section holds at most one table.

Only issues opened by a repository collaborator (author_association OWNER, MEMBER or
COLLABORATOR) are work items: anyone can open an issue, so an outsider's issue never places a
row, whatever its labels; it is named on stderr. Once the migration has run, BOARD.md carries
the GENERATED line and its rows come from the live issues, never from hand edits.

  board.py check                 the planned issues of BOARD.md render back to its live rows
  board.py check --repo o/r      once BOARD.md carries the GENERATED line: the committed file
                                 equals the board rendered from the live issues; before that,
                                 the same round trip as plain check
           [--base FILE]         fail if the base branch's BOARD.md carries the GENERATED line
                                 and this one does not, so a PR cannot switch the check off
  board.py render [--repo o/r]   print BOARD.md from the planned issues, or from GitHub's
                                 issues and PRs (GITHUB_TOKEN); PR disagreements go to stderr
"""
import argparse
import difflib
import json
import os
import pathlib
import re
import sys
import time
import urllib.error
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from doclint import RELEASE_CLASS, RELEASE_STATE  # noqa: E402
from metrics import OPEN_STATES, STATES  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARKER = "work-item"
GENERATED = "<!-- Generated by tools/board.py render --repo from the work-item issues: change an issue, not a row. -->"
COLLABORATORS = ("OWNER", "MEMBER", "COLLABORATOR")
ID = r"[A-Z][A-Za-z0-9]*(?:-[A-Za-z0-9]+)*(?: [a-z][A-Za-z0-9]*)*"  # "P2-2w c3 r1" too
BLOCK = re.compile(r"```board-row\n(.*?)\n```", re.S)
TIER = re.compile(r"\btier ([ABC])\b|\(([ABC])[;)]")
GATE = re.compile(r"\bMark approves\b|\bowner to confirm\b|\bwithout Mark\b|\bMark's approval\b")


def _lanes():
    """Team names from docs/LANES.md's Lanes table (first word of the Team cell)."""
    path, teams = ROOT / "docs" / "LANES.md", []
    if path.is_file():
        for line in path.read_text().splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if line.startswith("|") and len(cells) == 3 and cells[1] not in ("Team", "---"):
                teams.append(cells[1].split()[0])
    return tuple(teams) or ("primary",)


LANES = _lanes()
LANE = re.compile(r"\blane (" + "|".join(map(re.escape, LANES)) + r")\b")


def state_label(state):
    return f"state:{state}"


LABELS = {
    MARKER: "A BOARD.md row (tools/board.py)",
    **{state_label(s): f"BOARD state: {s}" for s in STATES},
    **{f"tier:{t}": f"Risk tier {t} (OPERATING §3)" for t in "ABC"},
    **{f"class:{c}": f"Finding class: {c} (OPERATING §2)" for c in ("blocker", "release", "later")},
    **{f"lane:{lane}": f"Built in the {lane} lane (docs/LANES.md)" for lane in LANES},
    "gate:mark": "Merge waits on Mark beyond the reviews",
}


def _cells(line):
    """A table line's cells; an escaped pipe (\\|) stays inside its cell, as GitHub renders it."""
    return [c.strip() for c in re.split(r"(?<!\\)\|", line.strip()[1:-1])]


def _table_lines(text):
    """Yield (line number, kind, section) for each line; kind is text, header, rule or row."""
    section, in_table, tables = "", False, {}
    for n, line in enumerate(text.splitlines()):
        if line.startswith("## "):
            section = line[3:]
        if not line.startswith("|"):
            in_table = False
            yield n, "text", section
        elif not in_table:
            in_table = True
            if "| State |" not in line:
                raise ValueError(f"BOARD.md:{n + 1}: a table without a State column")
            tables[section] = tables.get(section, 0) + 1
            if tables[section] > 1:
                raise ValueError(f"BOARD.md:{n + 1}: section {section!r} has a second table")
            yield n, "header", section
        elif set(line) <= set("|-: "):
            yield n, "rule", section
        else:
            yield n, "row", section


def rows(text):
    """Every BOARD row as {id, section, cells, state, rest}; cells are the middle columns."""
    lines, out = text.splitlines(), []
    for n, kind, section in _table_lines(text):
        if kind != "row":
            continue
        cells = _cells(lines[n])
        state = next((s for s in STATES if cells[-1].startswith(s)), None)
        if state is None:
            raise ValueError(f"BOARD.md:{n + 1}: {cells[0]}: state {cells[-1]!r} is not one of {', '.join(STATES)}")
        out.append({"id": cells[0], "section": section, "cells": cells[1:-1],
                    "state": state, "rest": cells[-1][len(state):]})
    return out


def _plain(markdown):
    return re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", markdown).replace("`", "")


def issue(row):
    """The planned issue for one row: title, labels and body (no number until created)."""
    if not re.fullmatch(ID, row["id"]):
        raise ValueError(f"BOARD.md: row ID {row['id']!r} is not an ID")
    text, state_cell = " ".join(row["cells"]), row["state"] + row["rest"]
    labels = [MARKER, state_label(row["state"])]
    tier = TIER.search(f"{text} {state_cell}")
    if tier:
        labels.append(f"tier:{tier.group(1) or tier.group(2)}")
    if RELEASE_STATE.search(state_cell) or RELEASE_CLASS.search(text):
        labels.append("class:release")
    lane = LANE.search(f"{text} {state_cell}")
    labels.append(f"lane:{lane.group(1) if lane else 'primary'}")
    if GATE.search(f"{text} {state_cell}"):
        labels.append("gate:mark")
    block = json.dumps({"section": row["section"], "cells": row["cells"], "rest": row["rest"]},
                       ensure_ascii=False, indent=1)
    return {"title": f"{row['id']}: {_plain(row['cells'][0])}"[:256], "labels": labels,
            "body": f"{row['cells'][0]}\n\n```board-row\n{block}\n```\n"}


def plan(text):
    """The issues a migration creates: one per live row, in BOARD order."""
    return [issue(r) for r in rows(text) if r["state"] in OPEN_STATES]


def _names(labels):
    return [x if isinstance(x, str) else x["name"] for x in labels]


def issue_id(item):
    m = re.match(rf"({ID}): ", item["title"])
    if not m:
        raise ValueError(f"issue #{item.get('number')}: title {item['title']!r} does not start with '<ID>: '")
    return m.group(1)


def row_of(item):
    """The row an issue renders as; raises ValueError naming the issue if it is malformed."""
    where = f"issue #{item.get('number')}"
    states = [x[len("state:"):] for x in _names(item["labels"]) if x.startswith("state:")]
    if len(states) != 1 or states[0] not in STATES:
        raise ValueError(f"{where}: needs exactly one state label of {', '.join(STATES)}, has {states}")
    m = BLOCK.search(item.get("body") or "")
    if not m:
        raise ValueError(f"{where}: body has no board-row block")
    try:
        data = json.loads(m.group(1))
        if not isinstance(data, dict):
            raise ValueError(f"expected an object, got {type(data).__name__}")
        section, cells, rest = data["section"], data["cells"], data["rest"]
    except (ValueError, KeyError) as e:
        raise ValueError(f"{where}: board-row block: {e}") from None
    # Body text reaches BOARD.md verbatim, so each value must stay inside its one cell.
    if not (isinstance(cells, list) and all(isinstance(v, str) for v in [section, *cells, rest])):
        raise ValueError(f"{where}: board-row section, cells and rest must be text")
    for v in [*cells, rest]:
        if "".join(v.splitlines()) != v or len(_cells(f"|{v}|")) != 1:
            raise ValueError(f"{where}: board-row value {v!r} has a line break or an unescaped |")
    return {"id": issue_id(item), "number": item["number"], "section": section,
            "cells": cells, "state": states[0], "rest": rest}


def render(skeleton, items):
    """BOARD.md: the skeleton's text with its rows replaced by the live rows of items."""
    lines = skeleton.splitlines()
    widths = {s: len(_cells(lines[n])) - 2 for n, kind, s in _table_lines(skeleton) if kind == "header"}
    by_section, seen = {}, set()
    for item in items:
        row = row_of(item)
        if row["id"] in seen:
            raise ValueError(f"issue #{row['number']}: a second issue for {row['id']}")
        seen.add(row["id"])
        if row["section"] not in widths:
            raise ValueError(f"issue #{row['number']}: no section {row['section']!r} in BOARD.md")
        if len(row["cells"]) != widths[row["section"]]:
            raise ValueError(f"issue #{row['number']}: {len(row['cells'])} middle cells, its table has {widths[row['section']]}")
        if row["state"] in OPEN_STATES:
            by_section.setdefault(row["section"], []).append(row)
    out = []
    for n, kind, section in _table_lines(skeleton):
        if kind == "row":
            continue
        out.append(lines[n])
        if kind == "rule":
            for row in sorted(by_section.get(section, []), key=lambda r: r["number"]):
                out.append("| " + " | ".join([row["id"], *row["cells"], row["state"] + row["rest"]]) + " |")
    return "\n".join(out) + ("\n" if skeleton.endswith("\n") else "")


def live(text):
    """BOARD.md with its terminal rows removed, line for line: what rendering must give."""
    lines = text.splitlines()
    keep = [lines[n] for n, kind, _ in _table_lines(text)
            if kind != "row" or _cells(lines[n])[-1].startswith(OPEN_STATES)]
    return "\n".join(keep) + ("\n" if text.endswith("\n") else "")


def pr_notes(items, prs):
    """Where an issue's state label and the PRs naming its ID (title prefix) disagree."""
    notes = []
    for item in items:
        if "pull_request" in item:
            continue
        row = row_of(item)
        if row["state"] not in OPEN_STATES:
            continue
        mine = [p for p in prs if re.match(rf"{re.escape(row['id'])}(?![A-Za-z0-9-])", p["title"])]
        opened = [p for p in mine if p["state"] == "open"]
        merged = [p for p in mine if p.get("merged_at")]
        if row["state"] in ("queued", "building") and opened:
            notes.append(f"{row['id']}: state {row['state']} but PR #{opened[0]['number']} is open")
        elif row["state"] == "in review" and not opened:
            notes.append(f"{row['id']}: state in review but no open PR names it")
        elif merged and not opened:
            notes.append(f"{row['id']}: state {row['state']} but PR #{merged[0]['number']} merged")
    return notes


def rate_limit_wait(code, headers, now):
    """Seconds to wait before retrying a refused call, or None if it was not rate limited.
    GitHub answers a primary or secondary rate limit with 403 or 429 and either retry-after or
    x-ratelimit-remaining 0 with x-ratelimit-reset (epoch seconds); other 403s are permissions."""
    if code not in (403, 429):
        return None
    if headers.get("retry-after", "").isdigit():
        return int(headers["retry-after"])
    if headers.get("x-ratelimit-remaining") == "0" and headers.get("x-ratelimit-reset", "").isdigit():
        return max(0, int(headers["x-ratelimit-reset"]) - int(now)) + 1
    return 60 if code == 429 else None


def call(req, sleep=time.sleep, now=time.time, tries=6):
    """urlopen(req) as JSON, waiting out rate limits; a refused call is not processed, so a retried
    POST does not create twice."""
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(req) as resp:
                return json.load(resp)
        except urllib.error.HTTPError as e:
            wait = rate_limit_wait(e.code, {k.lower(): v for k, v in e.headers.items()}, now())
            if wait is None or attempt == tries - 1:
                raise
            print(f"board: rate limited ({e.code}); retrying in {wait}s", file=sys.stderr)
            sleep(wait)


def github(path, method="GET", payload=None):
    """One GitHub REST call with GITHUB_TOKEN; GET follows pagination and returns the full list."""
    token = os.environ.get("GITHUB_TOKEN") or sys.exit("GITHUB_TOKEN is not set")
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
               "X-GitHub-Api-Version": "2022-11-28"}
    if method != "GET":
        return call(urllib.request.Request("https://api.github.com" + path, method=method, headers=headers,
                                           data=json.dumps(payload).encode()))
    out, page = [], 1
    while True:
        sep = "&" if "?" in path else "?"
        batch = call(urllib.request.Request(f"https://api.github.com{path}{sep}per_page=100&page={page}",
                                            headers=headers))
        out += batch
        if len(batch) < 100:
            return out
        page += 1


def work_items(fetch, repo):
    """The repository's open work-item issues opened by a collaborator; others are named on stderr."""
    items = []
    for i in fetch(f"/repos/{repo}/issues?state=open&labels={MARKER}"):
        if "pull_request" in i:
            continue
        if i.get("author_association") in COLLABORATORS:
            items.append(i)
        else:
            print(f"board: issue #{i.get('number')}: ignored, not opened by a collaborator", file=sys.stderr)
    return items


def main(argv=None, read=lambda: (ROOT / "BOARD.md").read_text(), fetch=github):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("command", choices=("check", "render"))
    ap.add_argument("--repo", help="owner/name: render from its issues and PRs instead of the plan")
    ap.add_argument("--base", metavar="FILE", help="the base branch's BOARD.md: once it carries the GENERATED line, so must this one")
    args = ap.parse_args(argv)
    text = read()
    if args.base and GENERATED in pathlib.Path(args.base).read_text() and GENERATED not in text:
        print("board: BOARD.md drops the GENERATED line its base carries; its rows come from the issues"
              " (retiring the generated board needs a ci.yml change)", file=sys.stderr)
        return 1
    try:
        if args.repo and (args.command == "render" or GENERATED in text):
            items = work_items(fetch, args.repo)
            for note in pr_notes(items, fetch(f"/repos/{args.repo}/pulls?state=all")):
                print(f"board: {note}", file=sys.stderr)
            generated = render(text, items)
            if args.command == "render":
                sys.stdout.write(generated)
                return 0
            if generated != text:
                diff = difflib.unified_diff(text.splitlines(), generated.splitlines(), "BOARD.md",
                                            f"rendered from {args.repo}", lineterm="")
                print(f"board: BOARD.md differs from the live issues; run tools/board.py render --repo {args.repo}"
                      " > BOARD.md, or wait for the board workflow:", *diff, sep="\n", file=sys.stderr)
                return 1
            print(f"board: BOARD.md equals the {len(items)} live issues of {args.repo}")
            return 0
        items = [dict(i, number=n) for n, i in enumerate(plan(text), start=1)]
        generated = render(text, items)
    except ValueError as e:
        print(f"board: {e}", file=sys.stderr)
        return 1
    if args.command == "render":
        sys.stdout.write(generated)
        return 0
    expected = live(text)
    if generated != expected:
        diff = difflib.unified_diff(expected.splitlines(), generated.splitlines(), "live rows", "generated", lineterm="")
        print("board: BOARD.md does not round-trip through its planned issues:", *diff, sep="\n", file=sys.stderr)
        return 1
    print(f"board: {len(items)} live rows round-trip through their planned issues")
    return 0


if __name__ == "__main__":
    sys.exit(main())
