#!/usr/bin/env python3
"""Requirement traceability: SPEC.md requirement IDs <-> tests and spikes.

Requirement IDs are bold tokens like **CRED-1** in SPEC.md.
Tests claim coverage with a marker comment anywhere in a file:  REQ: CRED-1, CRED-4
Usage:
  tools/trace.py            write TRACE.md
  tools/trace.py --check    fail if TRACE.md is stale or a marker cites an unknown ID
  tools/trace.py --gate A,B fail unless every listed ID has at least one covering file
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ID_DEF = re.compile(r"\*\*([A-Z]{2,4}-\d+[a-z]?)\*\*")
MARKER = re.compile(r"REQ:\s*([A-Z]{2,4}-\d+[a-z]?(?:\s*,\s*[A-Z]{2,4}-\d+[a-z]?)*)")
SCAN_DIRS = ("tests", "spikes", "src", "broker")
SKIP_SUFFIXES = {".png", ".jpg", ".img", ".iso", ".bin"}


def spec_ids(spec_text):
    seen = []
    for m in ID_DEF.finditer(spec_text):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def coverage(root):
    cov = {}
    for d in SCAN_DIRS:
        base = root / d
        if not base.is_dir():
            continue
        for f in sorted(base.rglob("*")):
            if not f.is_file() or f.suffix in SKIP_SUFFIXES:
                continue
            try:
                text = f.read_text(errors="ignore")
            except OSError:
                continue
            for m in MARKER.finditer(text):
                for rid in re.split(r"\s*,\s*", m.group(1)):
                    cov.setdefault(rid, set()).add(str(f.relative_to(root)))
    return cov


def render(ids, cov):
    covered = sum(1 for i in ids if i in cov)
    lines = [
        "# TRACE (generated by tools/trace.py; do not edit)",
        "",
        f"Covered: {covered} / {len(ids)} requirement IDs",
        "",
        "| ID | Covered by |",
        "|---|---|",
    ]
    for i in ids:
        files = ", ".join(f"`{f}`" for f in sorted(cov.get(i, ()))) or "—"
        lines.append(f"| {i} | {files} |")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--gate", default="")
    ap.add_argument("--root", default=str(ROOT))
    args = ap.parse_args(argv)
    root = pathlib.Path(args.root)

    ids = spec_ids((root / "SPEC.md").read_text())
    cov = coverage(root)
    out = render(ids, cov)
    trace = root / "TRACE.md"

    unknown = sorted(set(cov) - set(ids))
    if unknown:
        print("Markers cite IDs not in SPEC.md: " + ", ".join(unknown), file=sys.stderr)
        return 1
    if args.gate:
        missing = [g.strip() for g in args.gate.split(",") if g.strip() and g.strip() not in cov]
        if missing:
            print("Gate not covered: " + ", ".join(missing), file=sys.stderr)
            return 1
    if args.check:
        if not trace.exists() or trace.read_text() != out:
            print("TRACE.md is stale; run tools/trace.py", file=sys.stderr)
            return 1
        return 0
    trace.write_text(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
